### ISSUE TITLE
Write copy for homepage

### ISSUE THREAD

**Issue by tricoder42** [OneStopSource/onestopsource.io#2]
Minimalistic version:
- [x] Brand name
- [x] Claim? (subtitle, 1 sentence)
- [x] Short description (1 paragraph)
- [x] 4-5 photos + contact + short bio?
- [x] Location?

Anything else? Technologies we use (and can "insource")? References :trollface:?

@netman92 @Naomak @strx

**Comment by netman92** [comment]
References: everybody can write  ... me: Migration of big data, realtime processing ...
Location should be variable

**Comment by tricoder42** [comment]
Photos will be taken later. Copy is ready, needs proofreading though.
